trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

steps:
- task: AzureResourceGroupDeployment@2
  displayName: 'Validate Template'
  inputs:
    azureSubscription: 'Microsoft Azure Sponsorship-TestAA'
    resourceGroupName: '$(ResourceGroup)'
    location: '$(Location)'
    csmFile: azuredeploy.json
    overrideParameters: '-automationAccountName "$(accountName)"'
    deploymentMode: Validation

- task: GitHubRelease@0
  displayName: 'Create GitHub release'
  inputs:
    gitHubConnection: 'PoshSecurity-Github'
    repositoryName: 'poshsecurity/AzureAutomationDSC-CommonModules'
    target: master
    tagSource: manual
    tag: 'v$(Build.BuildNumber)'
    releaseNotesSource: input
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))